##
## EPITECH PROJECT, 2020
## Makefile
## File description:
## Makefile | https://www.gnu.org/software/make/manual/html_node/Implicit-Variables.html#Implicit-Variables
##

CC			= 	gcc

RM			= 	rm -rf

SRC			=	src/main.c

OBJ			=	$(SRC:.c=.o)

